version: 2

project_name: gh-pmu

before:
  hooks:
    - go mod tidy

builds:
  - id: gh-pmu
    main: .
    # gh extension expects binary named {os}-{arch} or {os}-{arch}.exe
    binary: "{{ .Os }}-{{ .Arch }}"
    no_unique_dist_dir: true
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/scooter-indie/gh-pmu/cmd.version={{.Version}}

# gh extension install expects raw binaries, not archives
archives:
  - id: gh-pmu
    formats:
      - binary
    name_template: "{{ .Binary }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: scooter-indie
    name: gh-pmu
  draft: false
  prerelease: auto
