@echo off
REM Launch Claude Code with gh-workflow reminder (bypass permissions mode)
REM Generated by IDPF Framework installer

claude --permission-mode "bypassPermissions" --append-system-prompt "IMPORTANT: Run /gh-workflow immediately" "Start"
